/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectog2;

import javax.swing.JOptionPane;

/**
 *
 * @author jcamp
 */
public class Modulo1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modulo1.class.getName());

    /**
     * Creates new form Modulo1
     */
    public Modulo1() {
        initComponents();
        actualizarArbitrosSedes();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        cantArbitros = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantEquipos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrePais = new javax.swing.JTextField();
        nombreDirector = new javax.swing.JTextField();
        agregarPaisDirectorB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreArbitro = new javax.swing.JTextField();
        agregarArbitroB = new javax.swing.JButton();
        nombreSede = new javax.swing.JTextField();
        agregarSedeB = new javax.swing.JButton();
        botonDemo = new javax.swing.JButton();
        cantArbitros1 = new javax.swing.JLabel();
        cantEstadios = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        cantArbitros.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cantArbitros.setText("00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(143, 166, 145));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido al Modulo 1");

        cantEquipos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cantEquipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24 Equipos", "32 Equipos", "48 Equipos", "64 Equipos" }));
        cantEquipos.addActionListener(this::cantEquiposActionPerformed);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("País");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Director Técnico");

        nombrePais.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        nombreDirector.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        agregarPaisDirectorB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        agregarPaisDirectorB.setText("Agregar");
        agregarPaisDirectorB.addActionListener(this::agregarPaisDirectorBActionPerformed);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Selección de Equipos");

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jButton2.setText("Volver");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registro de Equipos");

        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Total de Arbitros:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Total de Sedes/Estadios:");

        nombreArbitro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nombreArbitro.addActionListener(this::nombreArbitroActionPerformed);

        agregarArbitroB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        agregarArbitroB.setText("Agregar Arbitro");
        agregarArbitroB.addActionListener(this::agregarArbitroBActionPerformed);

        nombreSede.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nombreSede.addActionListener(this::nombreSedeActionPerformed);

        agregarSedeB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        agregarSedeB.setText("Agregar Sede");
        agregarSedeB.addActionListener(this::agregarSedeBActionPerformed);

        botonDemo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        botonDemo.setText("Generar Demo");
        botonDemo.addActionListener(this::botonDemoActionPerformed);

        cantArbitros1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cantArbitros1.setText("00");

        cantEstadios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cantEstadios.setText("00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonDemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(nombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(agregarSedeB, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(cantEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(agregarPaisDirectorB, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cantArbitros1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nombreArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(agregarArbitroB))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cantEstadios))))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarPaisDirectorB)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantArbitros1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarArbitroB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cantEstadios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarSedeB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDemo)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String equipos = "";
    String totalArbitros = "00";
    String totalSedes = "00";
    
    //limites de agregar arbitros y sedes con respecto a la cantidad de equipos seleccionada
    private int limiteArbitros = 0;
    private int limiteSedes = 0;
    private int limiteEquipos = 0;
    
    private int contadorArbitros = 0;
    private int contadorSedes=0;
    private int contadorPaises = 0;
    
    private Arbitros [] arbitros;
    private Sedes [] sedes;
    private Pais [] paises;
    
    private void actualizarArbitrosSedes(){
        cantArbitros1.setText("00/"+String.format("%02d", limiteArbitros));
        cantEstadios.setText("00/"+String.format("%02d", limiteSedes));
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (limiteEquipos==0){
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar la cantidad de equipos y registrar los datos.");
            return;
        }
        
        if(contadorPaises < limiteEquipos || contadorArbitros < limiteArbitros || contadorSedes < limiteSedes){
            JOptionPane.showMessageDialog(null, "Aún no se puede guardar. Se deben completar los registros.");
            return;
        }
        StringBuilder imprimirPaises = new StringBuilder();
        for (int i = 0; i < contadorPaises; i++) {
            if(paises[i]!=null){
                imprimirPaises.append(paises[i].toString());
                imprimirPaises.append("\n");
            }
        }
        JOptionPane.showMessageDialog(null, imprimirPaises);
        
        StringBuilder imprimirArbitros = new StringBuilder();
        for (int i = 0; i < contadorArbitros; i++) {
            if(arbitros[i]!=null){
                imprimirArbitros.append(arbitros[i].toString());
                imprimirArbitros.append("\n");
            }   
        }
        JOptionPane.showMessageDialog(null, imprimirArbitros);
        
        StringBuilder imprimirSedes = new StringBuilder();
        for (int i = 0; i < contadorSedes; i++) {
            if(sedes[i]!=null){
                imprimirSedes.append(sedes[i].toString());
                imprimirSedes.append("\n");
            }
        }
        JOptionPane.showMessageDialog(null, imprimirSedes);
        Menu ventanaMenu = new Menu();
        ventanaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void cantEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantEquiposActionPerformed
        if(cantEquipos.getSelectedItem()!=null){
            equipos = cantEquipos.getSelectedItem().toString().trim();
            if(equipos.equals("24 Equipos")){
                limiteEquipos =24;
                limiteArbitros =12;
                limiteSedes=6;
            }else if(equipos.equals("32 Equipos")){
                limiteEquipos =32;
                limiteArbitros = 16;
                limiteSedes = 8;
            }else if(equipos.equals("48 Equipos")){
                limiteEquipos=48;
                limiteArbitros = 24;
                limiteSedes=12;
            }else if(equipos.equals("64 Equipos")){
                limiteEquipos=64;
                limiteArbitros=32;
                limiteSedes=16;
            }
            paises = new Pais[limiteEquipos];
            arbitros = new Arbitros[limiteArbitros];
            sedes = new Sedes[limiteSedes];
            
            cantArbitros1.setText("00/"+String.format("%02d", limiteArbitros));
            cantEstadios.setText("00/"+String.format("%02d", limiteSedes));
        }
    }//GEN-LAST:event_cantEquiposActionPerformed

    private void nombreSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSedeActionPerformed

    private void nombreArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArbitroActionPerformed

    private void agregarArbitroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarArbitroBActionPerformed
        if(contadorArbitros>= limiteArbitros){
            JOptionPane.showMessageDialog(null, "Cantidad máxima de árbitros agregada.");
            return;
        }
        
        String nombreA = nombreArbitro.getText().trim();
        if (nombreA.isEmpty())return;
        
        arbitros [contadorArbitros]=new Arbitros(nombreA);
        contadorArbitros++;
        
        cantArbitros1.setText(String.format("%02d",contadorArbitros)+"/"+String.format("%02d",limiteArbitros));
        nombreArbitro.setText(""); //para limpiar el campo
    }//GEN-LAST:event_agregarArbitroBActionPerformed

    private void agregarSedeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSedeBActionPerformed
        if(contadorSedes>= limiteSedes){
            JOptionPane.showMessageDialog(null, "Cantidad máxima de sedes agregada.");
            return;
        }
        
        String nombreS = nombreSede.getText().trim();
        if (nombreS.isEmpty())return;
        
        sedes [contadorSedes]=new Sedes(nombreS);
        contadorSedes++;
        
        cantEstadios.setText(String.format("%02d",contadorSedes)+"/"+String.format("%02d",limiteSedes));
        nombreSede.setText("");
    }//GEN-LAST:event_agregarSedeBActionPerformed

    private void agregarPaisDirectorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPaisDirectorBActionPerformed
        if (limiteEquipos==0){
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar la cantidad de equipos.");
            return;
        }
        if(contadorPaises >= limiteEquipos){
            JOptionPane.showMessageDialog(null, "Cantidad máximas de equipos agregados.");
            return;
        }
        
        String pais = nombrePais.getText().trim();
        String dt = nombreDirector.getText().trim();
        
        if (pais.isEmpty() || dt.isEmpty()){
            JOptionPane.showMessageDialog(null, "Favor llenar los campos de Pais y Director Técnico.");
        }
        
        paises [contadorPaises]=new Pais(pais, dt);
        contadorPaises++;
        
        nombrePais.setText("");
        nombreDirector.setText("");
    }//GEN-LAST:event_agregarPaisDirectorBActionPerformed

    private void botonDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDemoActionPerformed
        if (limiteEquipos==0){
            JOptionPane.showMessageDialog(null, "Favor seleccione la cantidad de equipos antes de generar la demo.");
            return;
        }
        String []nombrePaises={"Argentina","Brasil", "Uruguay","Paraguay","Chile","Colombia","Ecuador","Perú","Veneuela","Bolivia", "México"
        +"Estados Unidos", "Canadá","Costa Rica","Panamá","Honduras","Jamaica","El Salvador","Guatemala","Trinidad y Tobago","Haití","Curazao"
        +"Japón","Corea del Sur", "Australia","Arabia Saudita","Irán","Irak","Catar","Emiratos Árabes Unidos","Uzbekistán","Jordania","Omán"
        +"China","Marruecos","Senegal","Egipto","Túnez","Argelia","Ghana","Nigeria","Camerún","Costa de Marfil", "Sudáfrica","República Democrática del Congo"
        +"Cabo Verde","Alemania","España","Francia","Inglaterra","Italia","Portugal","Países Bajos","Bélgica","Croacia","Suiza","Dinamarca","Suecia","Noruega"
        +"Polonia","Serbia","Turquía","Austria","República Checa","Escocia","Gales","Bosnia y Herzegovina","Ucrania","Nueva Zelanda", "Eslovaquia"};
        
        String []dts={"Thiago","Aitana","Gael", "Kiara","Elian","Amara","Dante","Zoe","Liam","Samira","Iker","Nayeli","Enzo","Briana","Milo","Celeste","Asher","Noemí","Elías","Renata"
        +"Erza","Arlet","DylanAbril","Ian","Mía","Christopher","Julieta","Noah","Miranda","Axel","Salomé","Bruno","Violeta","Brandron","Alondra","Benjamín"
        +"Raquel","León","Emilia","Matías","Fiorella","Adrián","Valeria","Issac","Alma","Damián","Darien","Fabián","Antonella","Ulises","Isadora","Teo"
        +"Elisa","Jacobo","Nayra","Ciro","Ariana","Máximo","Romina","Eros","Dafne","Santino","Ana","Orlando","Melina","Romeo","Aylin","Zaid","Ofelia"};
        
        String []arbitros1={"Diego","Sofía","Mateo", "Valentina","Santiago","Isabella","Sebastián","Camila","Nicolás","Daniela","Alejandro","Mariana"
        +"Daniel","Lucía","Gabriel","Elena","David","Gabriela","Samuel","Natalia","Néstor","Óscar","Marcelo","Eduardo","Mauricio","Roberto"
        +"Ronald","Zlatko","Dragan","Murat","Steve","Kasper","Luciano","Ralf","Julen","Montse","Sonia","Casey"};
        
        String []estadios={"Estadio Azteca","Estadio Akron","Estadio BBVA","MetLife Stadium","SoFi Stadium","Hard Rock Stadium","Lumen Field","Lincoln Financial Field"
        +"AT&T Stadium","Mercedes-Benz Stadium","Levi's Stadium","NRG Stadium","Arrowhead Stadium","Gillette Stadium","BC Place","BMO Field","Wembley Stadium"
        +"Santiago Bernabéu","Camp Nou","Allianz Arena","Maracaná","Lusail Stadium"};
        
        for (int i = 0; i < limiteEquipos; i++) {
            String p = nombrePaises[i%nombrePaises.length];
            String d = dts[i%dts.length];
            paises[i]=new Pais(p, d);
        }
        contadorPaises=limiteEquipos;
        
        for (int i = 0; i < limiteArbitros; i++) {
            arbitros[i]=new Arbitros(arbitros1[i%arbitros1.length]);
        }
        contadorArbitros=limiteArbitros;
        
        for (int i = 0; i < limiteSedes; i++) {
            sedes[i]=new Sedes(estadios[i%estadios.length]);
        }
        contadorSedes=limiteSedes;
        
        JOptionPane.showMessageDialog(null, "Demo generada\n-"+limiteEquipos+" Equipos generados.\n-"+limiteArbitros+" Árbitros generados.\n-"+limiteSedes+" Estadios genrados.");
    }//GEN-LAST:event_botonDemoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modulo1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarArbitroB;
    private javax.swing.JButton agregarPaisDirectorB;
    private javax.swing.JButton agregarSedeB;
    private javax.swing.JButton botonDemo;
    private javax.swing.JLabel cantArbitros;
    private javax.swing.JLabel cantArbitros1;
    private javax.swing.JComboBox<String> cantEquipos;
    private javax.swing.JLabel cantEstadios;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombreArbitro;
    private javax.swing.JTextField nombreDirector;
    private javax.swing.JTextField nombrePais;
    private javax.swing.JTextField nombreSede;
    // End of variables declaration//GEN-END:variables
}
